import * as React from 'react'
import { NewsGrid } from './NewsGrid'
import type { StoryObj, Meta } from '@storybook/react'
import { delay, http, HttpResponse } from 'msw'

const testData = {
  docs: [
    {
      id: 5,
      title: 'Dollar and Sense: The Financial Forecast',
      content: {
        root: {
          type: 'root',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              type: 'block',
              fields: {
                id: '674b01230e85b33825b696f0',
                style: 'info',
                content: {
                  root: {
                    type: 'root',
                    format: '',
                    indent: 0,
                    version: 1,
                    children: [
                      {
                        type: 'paragraph',
                        format: '',
                        indent: 0,
                        version: 1,
                        children: [
                          {
                            mode: 'normal',
                            text: 'Disclaimer: ',
                            type: 'text',
                            style: '',
                            detail: 0,
                            format: 1,
                            version: 1,
                          },
                          {
                            mode: 'normal',
                            text: 'This content is fabricated and for demonstration purposes only. To edit this post, ',
                            type: 'text',
                            style: '',
                            detail: 0,
                            format: 0,
                            version: 1,
                          },
                          {
                            type: 'link',
                            fields: { url: '/admin', newTab: true, linkType: 'custom' },
                            format: '',
                            indent: 0,
                            version: 3,
                            children: [
                              {
                                mode: 'normal',
                                text: 'navigate to the admin dashboard.',
                                type: 'text',
                                style: '',
                                detail: 0,
                                format: 0,
                                version: 1,
                              },
                            ],
                            direction: 'ltr',
                          },
                        ],
                        direction: 'ltr',
                        textFormat: 1,
                      },
                    ],
                    direction: 'ltr',
                  },
                },
                blockName: 'Disclaimer',
                blockType: 'banner',
              },
              format: '',
              version: 2,
            },
            {
              tag: 'h2',
              type: 'heading',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: "Money isn't just currency; ",
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
                {
                  mode: 'normal',
                  text: "it's a language. ",
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 2,
                  version: 1,
                },
                {
                  mode: 'normal',
                  text: 'Dive deep into its nuances, where strategy meets intuition in the vast sea of finance.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
            },
            {
              type: 'paragraph',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: "Money, in its essence, transcends the mere concept of coins and paper notes; it becomes a profound language that speaks of value, trust, and societal structures. Like any language, it possesses intricate nuances and subtleties that require a discerning understanding. It's in these depths where the calculated world of financial strategy collides with the raw, instinctive nature of human intuition. Just as a seasoned linguist might dissect the syntax and semantics of a sentence, a financial expert navigates the vast and tumultuous ocean of finance, guided not only by logic and data but also by gut feelings and foresight. Every transaction, investment, and financial decision becomes a dialogue in this expansive lexicon of commerce and value.",
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
              textFormat: 0,
            },
            {
              type: 'block',
              fields: {
                id: '674b01230e85b33825b696f1',
                media: {
                  id: 3,
                  alt: 'Curving abstract shapes with an orange and blue gradient',
                  caption: {
                    root: {
                      type: 'root',
                      format: '',
                      indent: 0,
                      version: 1,
                      children: [
                        {
                          type: 'paragraph',
                          format: '',
                          indent: 0,
                          version: 1,
                          children: [
                            {
                              mode: 'normal',
                              text: 'Photo by ',
                              type: 'text',
                              style: '',
                              detail: 0,
                              format: 0,
                              version: 1,
                            },
                            {
                              type: 'link',
                              fields: {
                                url: 'https://unsplash.com/@kirp',
                                newTab: true,
                                linkType: 'custom',
                              },
                              format: '',
                              indent: 0,
                              version: 2,
                              children: [
                                {
                                  mode: 'normal',
                                  text: 'Andrew Kliatskyi',
                                  type: 'text',
                                  style: '',
                                  detail: 0,
                                  format: 0,
                                  version: 1,
                                },
                              ],
                              direction: 'ltr',
                            },
                            {
                              mode: 'normal',
                              text: ' on Unsplash.',
                              type: 'text',
                              style: '',
                              detail: 0,
                              format: 0,
                              version: 1,
                            },
                          ],
                          direction: 'ltr',
                          textFormat: 0,
                        },
                      ],
                      direction: 'ltr',
                    },
                  },
                  updatedAt: '2024-11-30T12:12:09.410Z',
                  createdAt: '2024-11-30T12:12:09.410Z',
                  url: '/api/media/file/image-post1.webp',
                  thumbnailURL: '/api/media/file/image-post1-300x169.webp',
                  filename: 'image-post1.webp',
                  mimeType: 'image/webp',
                  filesize: 15924,
                  width: 1920,
                  height: 1080,
                  focalX: 50,
                  focalY: 50,
                  sizes: {
                    thumbnail: {
                      url: '/api/media/file/image-post1-300x169.webp',
                      width: 300,
                      height: 169,
                      mimeType: 'image/webp',
                      filesize: 1506,
                      filename: 'image-post1-300x169.webp',
                    },
                    square: {
                      url: '/api/media/file/image-post1-500x500.webp',
                      width: 500,
                      height: 500,
                      mimeType: 'image/webp',
                      filesize: 3718,
                      filename: 'image-post1-500x500.webp',
                    },
                    small: {
                      url: '/api/media/file/image-post1-600x338.webp',
                      width: 600,
                      height: 338,
                      mimeType: 'image/webp',
                      filesize: 3506,
                      filename: 'image-post1-600x338.webp',
                    },
                    medium: {
                      url: '/api/media/file/image-post1-900x506.webp',
                      width: 900,
                      height: 506,
                      mimeType: 'image/webp',
                      filesize: 5718,
                      filename: 'image-post1-900x506.webp',
                    },
                    large: {
                      url: '/api/media/file/image-post1-1400x788.webp',
                      width: 1400,
                      height: 788,
                      mimeType: 'image/webp',
                      filesize: 9810,
                      filename: 'image-post1-1400x788.webp',
                    },
                    xlarge: {
                      url: '/api/media/file/image-post1-1920x1080.webp',
                      width: 1920,
                      height: 1080,
                      mimeType: 'image/webp',
                      filesize: 15924,
                      filename: 'image-post1-1920x1080.webp',
                    },
                  },
                },
                blockName: '',
                blockType: 'mediaBlock',
              },
              format: '',
              version: 2,
            },
            {
              tag: 'h2',
              type: 'heading',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Stock Market Dynamics: Bulls, Bears, and the Uncertain Middle',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
            },
            {
              type: 'paragraph',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'The stock market is a realm of vast opportunity but also poses risks. Discover the forces that drive market trends and the strategies employed by top traders to navigate this complex ecosystem. From market analysis to understanding investor psychology, get a comprehensive insight into the world of stocks.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
              textFormat: 0,
            },
            {
              type: 'paragraph',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: "The stock market, often visualized as a bustling arena of numbers and ticker tapes, is as much about human behavior as it is about economics. It's a place where optimism, represented by the bullish rally, meets the caution of bearish downturns, with each vying to dictate the market's direction. But between these two extremes lies an uncertain middle ground, a zone populated by traders and investors who constantly weigh hope against fear. Successful navigation requires more than just financial acumen; it demands an understanding of collective sentiments and the ability to predict not just market movements, but also the reactions of other market participants. In this intricate dance of numbers and nerves, the most astute players are those who master both the hard data and the soft nuances of human behavior.",
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
              textFormat: 0,
            },
            {
              type: 'block',
              fields: {
                id: '674b01230e85b33825b696f2',
                style: 'info',
                content: {
                  root: {
                    type: 'root',
                    format: '',
                    indent: 0,
                    version: 1,
                    children: [
                      {
                        type: 'paragraph',
                        format: '',
                        indent: 0,
                        version: 1,
                        children: [
                          {
                            mode: 'normal',
                            text: "This content above is completely dynamic using custom layout building blocks configured in the CMS. This can be anything you'd like from rich text and images, to highly designed, complex components.",
                            type: 'text',
                            style: '',
                            detail: 0,
                            format: 0,
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        textFormat: 0,
                      },
                    ],
                    direction: 'ltr',
                  },
                },
                blockName: 'Dynamic components',
                blockType: 'banner',
              },
              format: '',
              version: 2,
            },
          ],
          direction: 'ltr',
        },
      },
      relatedPosts: [
        {
          id: 3,
          title: 'Digital Horizons: A Glimpse into Tomorrow',
          categories: [
            {
              id: 1,
              title: 'Technology',
              parent: null,
              breadcrumbs: [
                { id: '674b01210e85b33825b696be', doc: 1, url: null, label: 'Technology' },
              ],
              updatedAt: '2024-11-30T12:12:17.839Z',
              createdAt: '2024-11-30T12:12:17.742Z',
            },
          ],
          meta: {
            image: {
              id: 3,
              alt: 'Curving abstract shapes with an orange and blue gradient',
              caption: {
                root: {
                  type: 'root',
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      type: 'paragraph',
                      format: '',
                      indent: 0,
                      version: 1,
                      children: [
                        {
                          mode: 'normal',
                          text: 'Photo by ',
                          type: 'text',
                          style: '',
                          detail: 0,
                          format: 0,
                          version: 1,
                        },
                        {
                          type: 'link',
                          fields: {
                            url: 'https://unsplash.com/@kirp',
                            newTab: true,
                            linkType: 'custom',
                          },
                          format: '',
                          indent: 0,
                          version: 2,
                          children: [
                            {
                              mode: 'normal',
                              text: 'Andrew Kliatskyi',
                              type: 'text',
                              style: '',
                              detail: 0,
                              format: 0,
                              version: 1,
                            },
                          ],
                          direction: 'ltr',
                        },
                        {
                          mode: 'normal',
                          text: ' on Unsplash.',
                          type: 'text',
                          style: '',
                          detail: 0,
                          format: 0,
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                      textFormat: 0,
                    },
                  ],
                  direction: 'ltr',
                },
              },
              updatedAt: '2024-11-30T12:12:09.410Z',
              createdAt: '2024-11-30T12:12:09.410Z',
              url: '/api/media/file/image-post1.webp',
              thumbnailURL: '/api/media/file/image-post1-300x169.webp',
              filename: 'image-post1.webp',
              mimeType: 'image/webp',
              filesize: 15924,
              width: 1920,
              height: 1080,
              focalX: 50,
              focalY: 50,
              sizes: {
                thumbnail: {
                  url: '/api/media/file/image-post1-300x169.webp',
                  width: 300,
                  height: 169,
                  mimeType: 'image/webp',
                  filesize: 1506,
                  filename: 'image-post1-300x169.webp',
                },
                square: {
                  url: '/api/media/file/image-post1-500x500.webp',
                  width: 500,
                  height: 500,
                  mimeType: 'image/webp',
                  filesize: 3718,
                  filename: 'image-post1-500x500.webp',
                },
                small: {
                  url: '/api/media/file/image-post1-600x338.webp',
                  width: 600,
                  height: 338,
                  mimeType: 'image/webp',
                  filesize: 3506,
                  filename: 'image-post1-600x338.webp',
                },
                medium: {
                  url: '/api/media/file/image-post1-900x506.webp',
                  width: 900,
                  height: 506,
                  mimeType: 'image/webp',
                  filesize: 5718,
                  filename: 'image-post1-900x506.webp',
                },
                large: {
                  url: '/api/media/file/image-post1-1400x788.webp',
                  width: 1400,
                  height: 788,
                  mimeType: 'image/webp',
                  filesize: 9810,
                  filename: 'image-post1-1400x788.webp',
                },
                xlarge: {
                  url: '/api/media/file/image-post1-1920x1080.webp',
                  width: 1920,
                  height: 1080,
                  mimeType: 'image/webp',
                  filesize: 15924,
                  filename: 'image-post1-1920x1080.webp',
                },
              },
            },
            description:
              'Dive into the marvels of modern innovation, where the only constant is change. A journey where pixels and data converge to craft the future.',
          },
          slug: 'digital-horizons-a-glimpse-into-tomorrow',
        },
        {
          id: 4,
          title: 'Global Gaze: Beyond the Headlines',
          categories: [
            {
              id: 2,
              title: 'News',
              parent: null,
              breadcrumbs: [{ id: '674b01210e85b33825b696c0', doc: 2, url: null, label: 'News' }],
              updatedAt: '2024-11-30T12:12:17.919Z',
              createdAt: '2024-11-30T12:12:17.892Z',
            },
          ],
          meta: {
            image: {
              id: 4,
              alt: 'Curving abstract shapes with an orange and blue gradient',
              caption: {
                root: {
                  type: 'root',
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      type: 'paragraph',
                      format: '',
                      indent: 0,
                      version: 1,
                      children: [
                        {
                          mode: 'normal',
                          text: 'Photo by ',
                          type: 'text',
                          style: '',
                          detail: 0,
                          format: 0,
                          version: 1,
                        },
                        {
                          type: 'link',
                          fields: {
                            url: 'https://unsplash.com/@kirp',
                            newTab: true,
                            linkType: 'custom',
                          },
                          format: '',
                          indent: 0,
                          version: 2,
                          children: [
                            {
                              mode: 'normal',
                              text: 'Andrew Kliatskyi',
                              type: 'text',
                              style: '',
                              detail: 0,
                              format: 0,
                              version: 1,
                            },
                          ],
                          direction: 'ltr',
                        },
                        {
                          mode: 'normal',
                          text: ' on Unsplash.',
                          type: 'text',
                          style: '',
                          detail: 0,
                          format: 0,
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                      textFormat: 0,
                    },
                  ],
                  direction: 'ltr',
                },
              },
              updatedAt: '2024-11-30T12:12:11.139Z',
              createdAt: '2024-11-30T12:12:11.139Z',
              url: '/api/media/file/image-post2.webp',
              thumbnailURL: '/api/media/file/image-post2-300x169.webp',
              filename: 'image-post2.webp',
              mimeType: 'image/webp',
              filesize: 22332,
              width: 1920,
              height: 1080,
              focalX: 50,
              focalY: 50,
              sizes: {
                thumbnail: {
                  url: '/api/media/file/image-post2-300x169.webp',
                  width: 300,
                  height: 169,
                  mimeType: 'image/webp',
                  filesize: 2168,
                  filename: 'image-post2-300x169.webp',
                },
                square: {
                  url: '/api/media/file/image-post2-500x500.webp',
                  width: 500,
                  height: 500,
                  mimeType: 'image/webp',
                  filesize: 4816,
                  filename: 'image-post2-500x500.webp',
                },
                small: {
                  url: '/api/media/file/image-post2-600x338.webp',
                  width: 600,
                  height: 338,
                  mimeType: 'image/webp',
                  filesize: 4932,
                  filename: 'image-post2-600x338.webp',
                },
                medium: {
                  url: '/api/media/file/image-post2-900x506.webp',
                  width: 900,
                  height: 506,
                  mimeType: 'image/webp',
                  filesize: 7826,
                  filename: 'image-post2-900x506.webp',
                },
                large: {
                  url: '/api/media/file/image-post2-1400x788.webp',
                  width: 1400,
                  height: 788,
                  mimeType: 'image/webp',
                  filesize: 13594,
                  filename: 'image-post2-1400x788.webp',
                },
                xlarge: {
                  url: '/api/media/file/image-post2-1920x1080.webp',
                  width: 1920,
                  height: 1080,
                  mimeType: 'image/webp',
                  filesize: 22332,
                  filename: 'image-post2-1920x1080.webp',
                },
              },
            },
            description:
              'Explore the untold and overlooked. A magnified view into the corners of the world, where every story deserves its spotlight.',
          },
          slug: 'global-gaze-beyond-the-headlines',
        },
      ],
      categories: [
        {
          id: 3,
          title: 'Finance',
          parent: null,
          breadcrumbs: [{ id: '674b01210e85b33825b696c2', doc: 3, url: null, label: 'Finance' }],
          updatedAt: '2024-11-30T12:12:17.997Z',
          createdAt: '2024-11-30T12:12:17.934Z',
        },
      ],
      meta: {
        title: 'Dollar and Sense: The Financial Forecast',
        image: {
          id: 5,
          alt: 'Curving abstract shapes with an orange and blue gradient',
          caption: {
            root: {
              type: 'root',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  type: 'paragraph',
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Photo by ',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                    {
                      type: 'link',
                      fields: {
                        url: 'https://unsplash.com/@kirp',
                        newTab: true,
                        linkType: 'custom',
                      },
                      format: '',
                      indent: 0,
                      version: 2,
                      children: [
                        {
                          mode: 'normal',
                          text: 'Andrew Kliatskyi',
                          type: 'text',
                          style: '',
                          detail: 0,
                          format: 0,
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                    },
                    {
                      mode: 'normal',
                      text: ' on Unsplash.',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                  textFormat: 0,
                },
              ],
              direction: 'ltr',
            },
          },
          updatedAt: '2024-11-30T12:12:12.899Z',
          createdAt: '2024-11-30T12:12:12.899Z',
          url: '/api/media/file/image-post3.webp',
          thumbnailURL: '/api/media/file/image-post3-300x169.webp',
          filename: 'image-post3.webp',
          mimeType: 'image/webp',
          filesize: 14662,
          width: 1920,
          height: 1080,
          focalX: 50,
          focalY: 50,
          sizes: {
            thumbnail: {
              url: '/api/media/file/image-post3-300x169.webp',
              width: 300,
              height: 169,
              mimeType: 'image/webp',
              filesize: 1234,
              filename: 'image-post3-300x169.webp',
            },
            square: {
              url: '/api/media/file/image-post3-500x500.webp',
              width: 500,
              height: 500,
              mimeType: 'image/webp',
              filesize: 2668,
              filename: 'image-post3-500x500.webp',
            },
            small: {
              url: '/api/media/file/image-post3-600x338.webp',
              width: 600,
              height: 338,
              mimeType: 'image/webp',
              filesize: 3012,
              filename: 'image-post3-600x338.webp',
            },
            medium: {
              url: '/api/media/file/image-post3-900x506.webp',
              width: 900,
              height: 506,
              mimeType: 'image/webp',
              filesize: 4988,
              filename: 'image-post3-900x506.webp',
            },
            large: {
              url: '/api/media/file/image-post3-1400x788.webp',
              width: 1400,
              height: 788,
              mimeType: 'image/webp',
              filesize: 8998,
              filename: 'image-post3-1400x788.webp',
            },
            xlarge: {
              url: '/api/media/file/image-post3-1920x1080.webp',
              width: 1920,
              height: 1080,
              mimeType: 'image/webp',
              filesize: 14662,
              filename: 'image-post3-1920x1080.webp',
            },
          },
        },
        description:
          "Money isn't just currency; it's a language. Dive deep into its nuances, where strategy meets intuition in the vast sea of finance.",
      },
      publishedAt: '2024-11-30T12:12:18.582Z',
      authors: [
        {
          id: 2,
          name: 'Demo Author',
          workHistory: [],
          certifications: [],
          areasOfExpertise: [],
          profilePicture: null,
          updatedAt: '2024-11-30T12:12:08.651Z',
          createdAt: '2024-11-30T12:12:08.651Z',
          email: 'demo-author@payloadcms.com',
          loginAttempts: 0,
        },
      ],
      populatedAuthors: [{ id: 2, name: 'Demo Author' }],
      slug: 'dollar-and-sense-the-financial-forecast',
      slugLock: true,
      updatedAt: '2024-11-30T12:12:19.183Z',
      createdAt: '2024-11-30T12:12:18.580Z',
      _status: 'published',
    },
    {
      id: 4,
      title: 'Global Gaze: Beyond the Headlines',
      content: {
        root: {
          type: 'root',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              tag: 'h2',
              type: 'heading',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Explore the untold and overlooked. A magnified view into the corners of the world, where every story deserves its spotlight.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
            },
            {
              type: 'block',
              fields: {
                id: '674b01220e85b33825b696ea',
                style: 'info',
                content: {
                  root: {
                    type: 'root',
                    format: '',
                    indent: 0,
                    version: 1,
                    children: [
                      {
                        type: 'paragraph',
                        format: '',
                        indent: 0,
                        version: 1,
                        children: [
                          {
                            mode: 'normal',
                            text: 'Disclaimer:',
                            type: 'text',
                            style: '',
                            detail: 0,
                            format: 1,
                            version: 1,
                          },
                          {
                            mode: 'normal',
                            text: ' This content is fabricated and for demonstration purposes only. To edit this post, ',
                            type: 'text',
                            style: '',
                            detail: 0,
                            format: 0,
                            version: 1,
                          },
                          {
                            type: 'link',
                            fields: { url: '/admin', newTab: true, linkType: 'custom' },
                            format: '',
                            indent: 0,
                            version: 3,
                            children: [
                              {
                                mode: 'normal',
                                text: 'navigate to the admin dashboard.',
                                type: 'text',
                                style: '',
                                detail: 0,
                                format: 0,
                                version: 1,
                              },
                            ],
                            direction: 'ltr',
                          },
                        ],
                        direction: 'ltr',
                        textFormat: 1,
                      },
                    ],
                    direction: 'ltr',
                  },
                },
                blockName: 'Disclaimer',
                blockType: 'banner',
              },
              format: '',
              version: 2,
            },
            {
              tag: 'h2',
              type: 'heading',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'The Power of Resilience: Stories of Recovery and Hope',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
            },
            {
              type: 'paragraph',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: "Throughout history, regions across the globe have faced the devastating impact of natural disasters, the turbulence of political unrest, and the challenging ripples of economic downturns. In these moments of profound crisis, an often-underestimated force emerges: the indomitable resilience of the human spirit. These aren't just tales of mere survival, but stories of communities forging bonds, uniting with a collective purpose, and demonstrating an innate ability to overcome.",
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
              textFormat: 0,
            },
            {
              type: 'block',
              fields: {
                id: '674b01220e85b33825b696eb',
                media: {
                  id: 5,
                  alt: 'Curving abstract shapes with an orange and blue gradient',
                  caption: {
                    root: {
                      type: 'root',
                      format: '',
                      indent: 0,
                      version: 1,
                      children: [
                        {
                          type: 'paragraph',
                          format: '',
                          indent: 0,
                          version: 1,
                          children: [
                            {
                              mode: 'normal',
                              text: 'Photo by ',
                              type: 'text',
                              style: '',
                              detail: 0,
                              format: 0,
                              version: 1,
                            },
                            {
                              type: 'link',
                              fields: {
                                url: 'https://unsplash.com/@kirp',
                                newTab: true,
                                linkType: 'custom',
                              },
                              format: '',
                              indent: 0,
                              version: 2,
                              children: [
                                {
                                  mode: 'normal',
                                  text: 'Andrew Kliatskyi',
                                  type: 'text',
                                  style: '',
                                  detail: 0,
                                  format: 0,
                                  version: 1,
                                },
                              ],
                              direction: 'ltr',
                            },
                            {
                              mode: 'normal',
                              text: ' on Unsplash.',
                              type: 'text',
                              style: '',
                              detail: 0,
                              format: 0,
                              version: 1,
                            },
                          ],
                          direction: 'ltr',
                          textFormat: 0,
                        },
                      ],
                      direction: 'ltr',
                    },
                  },
                  updatedAt: '2024-11-30T12:12:12.899Z',
                  createdAt: '2024-11-30T12:12:12.899Z',
                  url: '/api/media/file/image-post3.webp',
                  thumbnailURL: '/api/media/file/image-post3-300x169.webp',
                  filename: 'image-post3.webp',
                  mimeType: 'image/webp',
                  filesize: 14662,
                  width: 1920,
                  height: 1080,
                  focalX: 50,
                  focalY: 50,
                  sizes: {
                    thumbnail: {
                      url: '/api/media/file/image-post3-300x169.webp',
                      width: 300,
                      height: 169,
                      mimeType: 'image/webp',
                      filesize: 1234,
                      filename: 'image-post3-300x169.webp',
                    },
                    square: {
                      url: '/api/media/file/image-post3-500x500.webp',
                      width: 500,
                      height: 500,
                      mimeType: 'image/webp',
                      filesize: 2668,
                      filename: 'image-post3-500x500.webp',
                    },
                    small: {
                      url: '/api/media/file/image-post3-600x338.webp',
                      width: 600,
                      height: 338,
                      mimeType: 'image/webp',
                      filesize: 3012,
                      filename: 'image-post3-600x338.webp',
                    },
                    medium: {
                      url: '/api/media/file/image-post3-900x506.webp',
                      width: 900,
                      height: 506,
                      mimeType: 'image/webp',
                      filesize: 4988,
                      filename: 'image-post3-900x506.webp',
                    },
                    large: {
                      url: '/api/media/file/image-post3-1400x788.webp',
                      width: 1400,
                      height: 788,
                      mimeType: 'image/webp',
                      filesize: 8998,
                      filename: 'image-post3-1400x788.webp',
                    },
                    xlarge: {
                      url: '/api/media/file/image-post3-1920x1080.webp',
                      width: 1920,
                      height: 1080,
                      mimeType: 'image/webp',
                      filesize: 14662,
                      filename: 'image-post3-1920x1080.webp',
                    },
                  },
                },
                blockName: '',
                blockType: 'mediaBlock',
              },
              format: '',
              version: 2,
            },
            {
              type: 'paragraph',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'From neighbors forming makeshift rescue teams during floods to entire cities rallying to rebuild after economic collapse, the essence of humanity is most evident in these acts of solidarity. As we delve into these narratives, we witness the transformative power of community spirit, where adversity becomes a catalyst for growth, unity, and a brighter, rebuilt future.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
              textFormat: 0,
            },
            {
              type: 'block',
              fields: {
                id: '674b01220e85b33825b696ec',
                style: 'info',
                content: {
                  root: {
                    type: 'root',
                    format: '',
                    indent: 0,
                    version: 1,
                    children: [
                      {
                        type: 'paragraph',
                        format: '',
                        indent: 0,
                        version: 1,
                        children: [
                          {
                            mode: 'normal',
                            text: "This content above is completely dynamic using custom layout building blocks configured in the CMS. This can be anything you'd like from rich text and images, to highly designed, complex components.",
                            type: 'text',
                            style: '',
                            detail: 0,
                            format: 0,
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        textFormat: 0,
                      },
                    ],
                    direction: 'ltr',
                  },
                },
                blockName: 'Dynamic components',
                blockType: 'banner',
              },
              format: '',
              version: 2,
            },
          ],
          direction: 'ltr',
        },
      },
      relatedPosts: [
        {
          id: 3,
          title: 'Digital Horizons: A Glimpse into Tomorrow',
          categories: [
            {
              id: 1,
              title: 'Technology',
              parent: null,
              breadcrumbs: [
                { id: '674b01210e85b33825b696be', doc: 1, url: null, label: 'Technology' },
              ],
              updatedAt: '2024-11-30T12:12:17.839Z',
              createdAt: '2024-11-30T12:12:17.742Z',
            },
          ],
          meta: {
            image: {
              id: 3,
              alt: 'Curving abstract shapes with an orange and blue gradient',
              caption: {
                root: {
                  type: 'root',
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      type: 'paragraph',
                      format: '',
                      indent: 0,
                      version: 1,
                      children: [
                        {
                          mode: 'normal',
                          text: 'Photo by ',
                          type: 'text',
                          style: '',
                          detail: 0,
                          format: 0,
                          version: 1,
                        },
                        {
                          type: 'link',
                          fields: {
                            url: 'https://unsplash.com/@kirp',
                            newTab: true,
                            linkType: 'custom',
                          },
                          format: '',
                          indent: 0,
                          version: 2,
                          children: [
                            {
                              mode: 'normal',
                              text: 'Andrew Kliatskyi',
                              type: 'text',
                              style: '',
                              detail: 0,
                              format: 0,
                              version: 1,
                            },
                          ],
                          direction: 'ltr',
                        },
                        {
                          mode: 'normal',
                          text: ' on Unsplash.',
                          type: 'text',
                          style: '',
                          detail: 0,
                          format: 0,
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                      textFormat: 0,
                    },
                  ],
                  direction: 'ltr',
                },
              },
              updatedAt: '2024-11-30T12:12:09.410Z',
              createdAt: '2024-11-30T12:12:09.410Z',
              url: '/api/media/file/image-post1.webp',
              thumbnailURL: '/api/media/file/image-post1-300x169.webp',
              filename: 'image-post1.webp',
              mimeType: 'image/webp',
              filesize: 15924,
              width: 1920,
              height: 1080,
              focalX: 50,
              focalY: 50,
              sizes: {
                thumbnail: {
                  url: '/api/media/file/image-post1-300x169.webp',
                  width: 300,
                  height: 169,
                  mimeType: 'image/webp',
                  filesize: 1506,
                  filename: 'image-post1-300x169.webp',
                },
                square: {
                  url: '/api/media/file/image-post1-500x500.webp',
                  width: 500,
                  height: 500,
                  mimeType: 'image/webp',
                  filesize: 3718,
                  filename: 'image-post1-500x500.webp',
                },
                small: {
                  url: '/api/media/file/image-post1-600x338.webp',
                  width: 600,
                  height: 338,
                  mimeType: 'image/webp',
                  filesize: 3506,
                  filename: 'image-post1-600x338.webp',
                },
                medium: {
                  url: '/api/media/file/image-post1-900x506.webp',
                  width: 900,
                  height: 506,
                  mimeType: 'image/webp',
                  filesize: 5718,
                  filename: 'image-post1-900x506.webp',
                },
                large: {
                  url: '/api/media/file/image-post1-1400x788.webp',
                  width: 1400,
                  height: 788,
                  mimeType: 'image/webp',
                  filesize: 9810,
                  filename: 'image-post1-1400x788.webp',
                },
                xlarge: {
                  url: '/api/media/file/image-post1-1920x1080.webp',
                  width: 1920,
                  height: 1080,
                  mimeType: 'image/webp',
                  filesize: 15924,
                  filename: 'image-post1-1920x1080.webp',
                },
              },
            },
            description:
              'Dive into the marvels of modern innovation, where the only constant is change. A journey where pixels and data converge to craft the future.',
          },
          slug: 'digital-horizons-a-glimpse-into-tomorrow',
        },
        {
          id: 5,
          title: 'Dollar and Sense: The Financial Forecast',
          categories: [
            {
              id: 3,
              title: 'Finance',
              parent: null,
              breadcrumbs: [
                { id: '674b01210e85b33825b696c2', doc: 3, url: null, label: 'Finance' },
              ],
              updatedAt: '2024-11-30T12:12:17.997Z',
              createdAt: '2024-11-30T12:12:17.934Z',
            },
          ],
          meta: {
            image: {
              id: 5,
              alt: 'Curving abstract shapes with an orange and blue gradient',
              caption: {
                root: {
                  type: 'root',
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      type: 'paragraph',
                      format: '',
                      indent: 0,
                      version: 1,
                      children: [
                        {
                          mode: 'normal',
                          text: 'Photo by ',
                          type: 'text',
                          style: '',
                          detail: 0,
                          format: 0,
                          version: 1,
                        },
                        {
                          type: 'link',
                          fields: {
                            url: 'https://unsplash.com/@kirp',
                            newTab: true,
                            linkType: 'custom',
                          },
                          format: '',
                          indent: 0,
                          version: 2,
                          children: [
                            {
                              mode: 'normal',
                              text: 'Andrew Kliatskyi',
                              type: 'text',
                              style: '',
                              detail: 0,
                              format: 0,
                              version: 1,
                            },
                          ],
                          direction: 'ltr',
                        },
                        {
                          mode: 'normal',
                          text: ' on Unsplash.',
                          type: 'text',
                          style: '',
                          detail: 0,
                          format: 0,
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                      textFormat: 0,
                    },
                  ],
                  direction: 'ltr',
                },
              },
              updatedAt: '2024-11-30T12:12:12.899Z',
              createdAt: '2024-11-30T12:12:12.899Z',
              url: '/api/media/file/image-post3.webp',
              thumbnailURL: '/api/media/file/image-post3-300x169.webp',
              filename: 'image-post3.webp',
              mimeType: 'image/webp',
              filesize: 14662,
              width: 1920,
              height: 1080,
              focalX: 50,
              focalY: 50,
              sizes: {
                thumbnail: {
                  url: '/api/media/file/image-post3-300x169.webp',
                  width: 300,
                  height: 169,
                  mimeType: 'image/webp',
                  filesize: 1234,
                  filename: 'image-post3-300x169.webp',
                },
                square: {
                  url: '/api/media/file/image-post3-500x500.webp',
                  width: 500,
                  height: 500,
                  mimeType: 'image/webp',
                  filesize: 2668,
                  filename: 'image-post3-500x500.webp',
                },
                small: {
                  url: '/api/media/file/image-post3-600x338.webp',
                  width: 600,
                  height: 338,
                  mimeType: 'image/webp',
                  filesize: 3012,
                  filename: 'image-post3-600x338.webp',
                },
                medium: {
                  url: '/api/media/file/image-post3-900x506.webp',
                  width: 900,
                  height: 506,
                  mimeType: 'image/webp',
                  filesize: 4988,
                  filename: 'image-post3-900x506.webp',
                },
                large: {
                  url: '/api/media/file/image-post3-1400x788.webp',
                  width: 1400,
                  height: 788,
                  mimeType: 'image/webp',
                  filesize: 8998,
                  filename: 'image-post3-1400x788.webp',
                },
                xlarge: {
                  url: '/api/media/file/image-post3-1920x1080.webp',
                  width: 1920,
                  height: 1080,
                  mimeType: 'image/webp',
                  filesize: 14662,
                  filename: 'image-post3-1920x1080.webp',
                },
              },
            },
            description:
              "Money isn't just currency; it's a language. Dive deep into its nuances, where strategy meets intuition in the vast sea of finance.",
          },
          slug: 'dollar-and-sense-the-financial-forecast',
        },
      ],
      categories: [
        {
          id: 2,
          title: 'News',
          parent: null,
          breadcrumbs: [{ id: '674b01210e85b33825b696c0', doc: 2, url: null, label: 'News' }],
          updatedAt: '2024-11-30T12:12:17.919Z',
          createdAt: '2024-11-30T12:12:17.892Z',
        },
      ],
      meta: {
        title: 'Global Gaze: Beyond the Headlines',
        image: {
          id: 4,
          alt: 'Curving abstract shapes with an orange and blue gradient',
          caption: {
            root: {
              type: 'root',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  type: 'paragraph',
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Photo by ',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                    {
                      type: 'link',
                      fields: {
                        url: 'https://unsplash.com/@kirp',
                        newTab: true,
                        linkType: 'custom',
                      },
                      format: '',
                      indent: 0,
                      version: 2,
                      children: [
                        {
                          mode: 'normal',
                          text: 'Andrew Kliatskyi',
                          type: 'text',
                          style: '',
                          detail: 0,
                          format: 0,
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                    },
                    {
                      mode: 'normal',
                      text: ' on Unsplash.',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                  textFormat: 0,
                },
              ],
              direction: 'ltr',
            },
          },
          updatedAt: '2024-11-30T12:12:11.139Z',
          createdAt: '2024-11-30T12:12:11.139Z',
          url: '/api/media/file/image-post2.webp',
          thumbnailURL: '/api/media/file/image-post2-300x169.webp',
          filename: 'image-post2.webp',
          mimeType: 'image/webp',
          filesize: 22332,
          width: 1920,
          height: 1080,
          focalX: 50,
          focalY: 50,
          sizes: {
            thumbnail: {
              url: '/api/media/file/image-post2-300x169.webp',
              width: 300,
              height: 169,
              mimeType: 'image/webp',
              filesize: 2168,
              filename: 'image-post2-300x169.webp',
            },
            square: {
              url: '/api/media/file/image-post2-500x500.webp',
              width: 500,
              height: 500,
              mimeType: 'image/webp',
              filesize: 4816,
              filename: 'image-post2-500x500.webp',
            },
            small: {
              url: '/api/media/file/image-post2-600x338.webp',
              width: 600,
              height: 338,
              mimeType: 'image/webp',
              filesize: 4932,
              filename: 'image-post2-600x338.webp',
            },
            medium: {
              url: '/api/media/file/image-post2-900x506.webp',
              width: 900,
              height: 506,
              mimeType: 'image/webp',
              filesize: 7826,
              filename: 'image-post2-900x506.webp',
            },
            large: {
              url: '/api/media/file/image-post2-1400x788.webp',
              width: 1400,
              height: 788,
              mimeType: 'image/webp',
              filesize: 13594,
              filename: 'image-post2-1400x788.webp',
            },
            xlarge: {
              url: '/api/media/file/image-post2-1920x1080.webp',
              width: 1920,
              height: 1080,
              mimeType: 'image/webp',
              filesize: 22332,
              filename: 'image-post2-1920x1080.webp',
            },
          },
        },
        description:
          'Explore the untold and overlooked. A magnified view into the corners of the world, where every story deserves its spotlight.',
      },
      publishedAt: '2024-11-30T12:12:18.402Z',
      authors: [
        {
          id: 2,
          name: 'Demo Author',
          workHistory: [],
          certifications: [],
          areasOfExpertise: [],
          profilePicture: null,
          updatedAt: '2024-11-30T12:12:08.651Z',
          createdAt: '2024-11-30T12:12:08.651Z',
          email: 'demo-author@payloadcms.com',
          loginAttempts: 0,
        },
      ],
      populatedAuthors: [{ id: 2, name: 'Demo Author' }],
      slug: 'global-gaze-beyond-the-headlines',
      slugLock: true,
      updatedAt: '2024-11-30T12:12:19.003Z',
      createdAt: '2024-11-30T12:12:18.397Z',
      _status: 'published',
    },
    {
      id: 3,
      title: 'Digital Horizons: A Glimpse into Tomorrow',
      content: {
        root: {
          type: 'root',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              tag: 'h2',
              type: 'heading',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Dive into the marvels of modern innovation, where the only constant is change. A journey where pixels and data converge to craft the future.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
            },
            {
              type: 'block',
              fields: {
                id: '674b01220e85b33825b696e0',
                style: 'info',
                content: {
                  root: {
                    type: 'root',
                    format: '',
                    indent: 0,
                    version: 1,
                    children: [
                      {
                        type: 'paragraph',
                        format: '',
                        indent: 0,
                        version: 1,
                        children: [
                          {
                            mode: 'normal',
                            text: 'Disclaimer:',
                            type: 'text',
                            style: '',
                            detail: 0,
                            format: 1,
                            version: 1,
                          },
                          {
                            mode: 'normal',
                            text: ' This content is fabricated and for demonstration purposes only. To edit this post, ',
                            type: 'text',
                            style: '',
                            detail: 0,
                            format: 0,
                            version: 1,
                          },
                          {
                            type: 'link',
                            fields: { url: '/admin', newTab: true, linkType: 'custom' },
                            format: '',
                            indent: 0,
                            version: 3,
                            children: [
                              {
                                mode: 'normal',
                                text: 'navigate to the admin dashboard',
                                type: 'text',
                                style: '',
                                detail: 0,
                                format: 0,
                                version: 1,
                              },
                            ],
                            direction: 'ltr',
                          },
                          {
                            mode: 'normal',
                            text: '.',
                            type: 'text',
                            style: '',
                            detail: 0,
                            format: 0,
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        textFormat: 0,
                      },
                    ],
                    direction: 'ltr',
                  },
                },
                blockName: 'Disclaimer',
                blockType: 'banner',
              },
              format: '',
              version: 2,
            },
            {
              tag: 'h2',
              type: 'heading',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'The Rise of AI and Machine Learning',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
            },
            {
              type: 'paragraph',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'We find ourselves in a transformative era where artificial intelligence (AI) stands at the forefront of technological evolution. The ripple effects of its advancements are reshaping industries at an unprecedented pace. No longer are businesses bound by the limitations of tedious, manual processes. Instead, sophisticated machines, fueled by vast amounts of historical data, are now capable of making decisions previously left to human intuition. These intelligent systems are not only optimizing operations but also pioneering innovative approaches, heralding a new age of business transformation worldwide. ',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
              textFormat: 0,
            },
            {
              tag: 'h4',
              type: 'heading',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'To demonstrate basic AI functionality, here is a javascript snippet that makes a POST request to a generic AI API in order to generate text based on a prompt. ',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
            },
            {
              type: 'block',
              fields: {
                id: '674b01220e85b33825b696e1',
                code: "async function generateText(prompt) {\n    const apiKey = 'your-api-key';\n    const apiUrl = 'https://api.example.com/generate-text';\n\n    const response = await fetch(apiUrl, {\n        method: 'POST',\n        headers: {\n            'Content-Type': 'application/json',\n            'Authorization': `Bearer ${apiKey}`\n        },\n        body: JSON.stringify({\n            model: 'text-generation-model',\n            prompt: prompt,\n            max_tokens: 50\n        })\n    });\n\n    const data = await response.json();\n    // console.log(data.choices[0].text.trim());\n}\n\n// Example usage\ngenerateText(\"Once upon a time in a faraway land,\");\n",
                language: 'javascript',
                blockName: 'Generate Text',
                blockType: 'code',
              },
              format: '',
              version: 2,
            },
            {
              tag: 'h2',
              type: 'heading',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'IoT: Connecting the World Around Us',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
            },
            {
              type: 'paragraph',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: "In today's rapidly evolving technological landscape, the Internet of Things (IoT) stands out as a revolutionary force. From transforming our residences with smart home systems to redefining transportation through connected cars, IoT's influence is palpable in nearly every facet of our daily lives.",
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
              textFormat: 0,
            },
            {
              type: 'paragraph',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: "This technology hinges on the seamless integration of devices and systems, allowing them to communicate and collaborate effortlessly. With each connected device, we move a step closer to a world where convenience and efficiency are embedded in the very fabric of our existence. As a result, we're transitioning into an era where our surroundings intuitively respond to our needs, heralding a smarter and more interconnected global community.",
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
              textFormat: 0,
            },
            {
              type: 'block',
              fields: {
                id: '674b01220e85b33825b696e2',
                media: {
                  id: 4,
                  alt: 'Curving abstract shapes with an orange and blue gradient',
                  caption: {
                    root: {
                      type: 'root',
                      format: '',
                      indent: 0,
                      version: 1,
                      children: [
                        {
                          type: 'paragraph',
                          format: '',
                          indent: 0,
                          version: 1,
                          children: [
                            {
                              mode: 'normal',
                              text: 'Photo by ',
                              type: 'text',
                              style: '',
                              detail: 0,
                              format: 0,
                              version: 1,
                            },
                            {
                              type: 'link',
                              fields: {
                                url: 'https://unsplash.com/@kirp',
                                newTab: true,
                                linkType: 'custom',
                              },
                              format: '',
                              indent: 0,
                              version: 2,
                              children: [
                                {
                                  mode: 'normal',
                                  text: 'Andrew Kliatskyi',
                                  type: 'text',
                                  style: '',
                                  detail: 0,
                                  format: 0,
                                  version: 1,
                                },
                              ],
                              direction: 'ltr',
                            },
                            {
                              mode: 'normal',
                              text: ' on Unsplash.',
                              type: 'text',
                              style: '',
                              detail: 0,
                              format: 0,
                              version: 1,
                            },
                          ],
                          direction: 'ltr',
                          textFormat: 0,
                        },
                      ],
                      direction: 'ltr',
                    },
                  },
                  updatedAt: '2024-11-30T12:12:11.139Z',
                  createdAt: '2024-11-30T12:12:11.139Z',
                  url: '/api/media/file/image-post2.webp',
                  thumbnailURL: '/api/media/file/image-post2-300x169.webp',
                  filename: 'image-post2.webp',
                  mimeType: 'image/webp',
                  filesize: 22332,
                  width: 1920,
                  height: 1080,
                  focalX: 50,
                  focalY: 50,
                  sizes: {
                    thumbnail: {
                      url: '/api/media/file/image-post2-300x169.webp',
                      width: 300,
                      height: 169,
                      mimeType: 'image/webp',
                      filesize: 2168,
                      filename: 'image-post2-300x169.webp',
                    },
                    square: {
                      url: '/api/media/file/image-post2-500x500.webp',
                      width: 500,
                      height: 500,
                      mimeType: 'image/webp',
                      filesize: 4816,
                      filename: 'image-post2-500x500.webp',
                    },
                    small: {
                      url: '/api/media/file/image-post2-600x338.webp',
                      width: 600,
                      height: 338,
                      mimeType: 'image/webp',
                      filesize: 4932,
                      filename: 'image-post2-600x338.webp',
                    },
                    medium: {
                      url: '/api/media/file/image-post2-900x506.webp',
                      width: 900,
                      height: 506,
                      mimeType: 'image/webp',
                      filesize: 7826,
                      filename: 'image-post2-900x506.webp',
                    },
                    large: {
                      url: '/api/media/file/image-post2-1400x788.webp',
                      width: 1400,
                      height: 788,
                      mimeType: 'image/webp',
                      filesize: 13594,
                      filename: 'image-post2-1400x788.webp',
                    },
                    xlarge: {
                      url: '/api/media/file/image-post2-1920x1080.webp',
                      width: 1920,
                      height: 1080,
                      mimeType: 'image/webp',
                      filesize: 22332,
                      filename: 'image-post2-1920x1080.webp',
                    },
                  },
                },
                blockName: '',
                blockType: 'mediaBlock',
              },
              format: '',
              version: 2,
            },
            {
              type: 'block',
              fields: {
                id: '674b01220e85b33825b696e3',
                style: 'info',
                content: {
                  root: {
                    type: 'root',
                    format: '',
                    indent: 0,
                    version: 1,
                    children: [
                      {
                        type: 'paragraph',
                        format: '',
                        indent: 0,
                        version: 1,
                        children: [
                          {
                            mode: 'normal',
                            text: "This content above is completely dynamic using custom layout building blocks configured in the CMS. This can be anything you'd like from rich text and images, to highly designed, complex components.",
                            type: 'text',
                            style: '',
                            detail: 0,
                            format: 0,
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        textFormat: 0,
                      },
                    ],
                    direction: 'ltr',
                  },
                },
                blockName: 'Dynamic Components',
                blockType: 'banner',
              },
              format: '',
              version: 2,
            },
          ],
          direction: 'ltr',
        },
      },
      relatedPosts: [
        {
          id: 4,
          title: 'Global Gaze: Beyond the Headlines',
          categories: [
            {
              id: 2,
              title: 'News',
              parent: null,
              breadcrumbs: [{ id: '674b01210e85b33825b696c0', doc: 2, url: null, label: 'News' }],
              updatedAt: '2024-11-30T12:12:17.919Z',
              createdAt: '2024-11-30T12:12:17.892Z',
            },
          ],
          meta: {
            image: {
              id: 4,
              alt: 'Curving abstract shapes with an orange and blue gradient',
              caption: {
                root: {
                  type: 'root',
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      type: 'paragraph',
                      format: '',
                      indent: 0,
                      version: 1,
                      children: [
                        {
                          mode: 'normal',
                          text: 'Photo by ',
                          type: 'text',
                          style: '',
                          detail: 0,
                          format: 0,
                          version: 1,
                        },
                        {
                          type: 'link',
                          fields: {
                            url: 'https://unsplash.com/@kirp',
                            newTab: true,
                            linkType: 'custom',
                          },
                          format: '',
                          indent: 0,
                          version: 2,
                          children: [
                            {
                              mode: 'normal',
                              text: 'Andrew Kliatskyi',
                              type: 'text',
                              style: '',
                              detail: 0,
                              format: 0,
                              version: 1,
                            },
                          ],
                          direction: 'ltr',
                        },
                        {
                          mode: 'normal',
                          text: ' on Unsplash.',
                          type: 'text',
                          style: '',
                          detail: 0,
                          format: 0,
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                      textFormat: 0,
                    },
                  ],
                  direction: 'ltr',
                },
              },
              updatedAt: '2024-11-30T12:12:11.139Z',
              createdAt: '2024-11-30T12:12:11.139Z',
              url: '/api/media/file/image-post2.webp',
              thumbnailURL: '/api/media/file/image-post2-300x169.webp',
              filename: 'image-post2.webp',
              mimeType: 'image/webp',
              filesize: 22332,
              width: 1920,
              height: 1080,
              focalX: 50,
              focalY: 50,
              sizes: {
                thumbnail: {
                  url: '/api/media/file/image-post2-300x169.webp',
                  width: 300,
                  height: 169,
                  mimeType: 'image/webp',
                  filesize: 2168,
                  filename: 'image-post2-300x169.webp',
                },
                square: {
                  url: '/api/media/file/image-post2-500x500.webp',
                  width: 500,
                  height: 500,
                  mimeType: 'image/webp',
                  filesize: 4816,
                  filename: 'image-post2-500x500.webp',
                },
                small: {
                  url: '/api/media/file/image-post2-600x338.webp',
                  width: 600,
                  height: 338,
                  mimeType: 'image/webp',
                  filesize: 4932,
                  filename: 'image-post2-600x338.webp',
                },
                medium: {
                  url: '/api/media/file/image-post2-900x506.webp',
                  width: 900,
                  height: 506,
                  mimeType: 'image/webp',
                  filesize: 7826,
                  filename: 'image-post2-900x506.webp',
                },
                large: {
                  url: '/api/media/file/image-post2-1400x788.webp',
                  width: 1400,
                  height: 788,
                  mimeType: 'image/webp',
                  filesize: 13594,
                  filename: 'image-post2-1400x788.webp',
                },
                xlarge: {
                  url: '/api/media/file/image-post2-1920x1080.webp',
                  width: 1920,
                  height: 1080,
                  mimeType: 'image/webp',
                  filesize: 22332,
                  filename: 'image-post2-1920x1080.webp',
                },
              },
            },
            description:
              'Explore the untold and overlooked. A magnified view into the corners of the world, where every story deserves its spotlight.',
          },
          slug: 'global-gaze-beyond-the-headlines',
        },
        {
          id: 5,
          title: 'Dollar and Sense: The Financial Forecast',
          categories: [
            {
              id: 3,
              title: 'Finance',
              parent: null,
              breadcrumbs: [
                { id: '674b01210e85b33825b696c2', doc: 3, url: null, label: 'Finance' },
              ],
              updatedAt: '2024-11-30T12:12:17.997Z',
              createdAt: '2024-11-30T12:12:17.934Z',
            },
          ],
          meta: {
            image: {
              id: 5,
              alt: 'Curving abstract shapes with an orange and blue gradient',
              caption: {
                root: {
                  type: 'root',
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      type: 'paragraph',
                      format: '',
                      indent: 0,
                      version: 1,
                      children: [
                        {
                          mode: 'normal',
                          text: 'Photo by ',
                          type: 'text',
                          style: '',
                          detail: 0,
                          format: 0,
                          version: 1,
                        },
                        {
                          type: 'link',
                          fields: {
                            url: 'https://unsplash.com/@kirp',
                            newTab: true,
                            linkType: 'custom',
                          },
                          format: '',
                          indent: 0,
                          version: 2,
                          children: [
                            {
                              mode: 'normal',
                              text: 'Andrew Kliatskyi',
                              type: 'text',
                              style: '',
                              detail: 0,
                              format: 0,
                              version: 1,
                            },
                          ],
                          direction: 'ltr',
                        },
                        {
                          mode: 'normal',
                          text: ' on Unsplash.',
                          type: 'text',
                          style: '',
                          detail: 0,
                          format: 0,
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                      textFormat: 0,
                    },
                  ],
                  direction: 'ltr',
                },
              },
              updatedAt: '2024-11-30T12:12:12.899Z',
              createdAt: '2024-11-30T12:12:12.899Z',
              url: '/api/media/file/image-post3.webp',
              thumbnailURL: '/api/media/file/image-post3-300x169.webp',
              filename: 'image-post3.webp',
              mimeType: 'image/webp',
              filesize: 14662,
              width: 1920,
              height: 1080,
              focalX: 50,
              focalY: 50,
              sizes: {
                thumbnail: {
                  url: '/api/media/file/image-post3-300x169.webp',
                  width: 300,
                  height: 169,
                  mimeType: 'image/webp',
                  filesize: 1234,
                  filename: 'image-post3-300x169.webp',
                },
                square: {
                  url: '/api/media/file/image-post3-500x500.webp',
                  width: 500,
                  height: 500,
                  mimeType: 'image/webp',
                  filesize: 2668,
                  filename: 'image-post3-500x500.webp',
                },
                small: {
                  url: '/api/media/file/image-post3-600x338.webp',
                  width: 600,
                  height: 338,
                  mimeType: 'image/webp',
                  filesize: 3012,
                  filename: 'image-post3-600x338.webp',
                },
                medium: {
                  url: '/api/media/file/image-post3-900x506.webp',
                  width: 900,
                  height: 506,
                  mimeType: 'image/webp',
                  filesize: 4988,
                  filename: 'image-post3-900x506.webp',
                },
                large: {
                  url: '/api/media/file/image-post3-1400x788.webp',
                  width: 1400,
                  height: 788,
                  mimeType: 'image/webp',
                  filesize: 8998,
                  filename: 'image-post3-1400x788.webp',
                },
                xlarge: {
                  url: '/api/media/file/image-post3-1920x1080.webp',
                  width: 1920,
                  height: 1080,
                  mimeType: 'image/webp',
                  filesize: 14662,
                  filename: 'image-post3-1920x1080.webp',
                },
              },
            },
            description:
              "Money isn't just currency; it's a language. Dive deep into its nuances, where strategy meets intuition in the vast sea of finance.",
          },
          slug: 'dollar-and-sense-the-financial-forecast',
        },
      ],
      categories: [
        {
          id: 1,
          title: 'Technology',
          parent: null,
          breadcrumbs: [{ id: '674b01210e85b33825b696be', doc: 1, url: null, label: 'Technology' }],
          updatedAt: '2024-11-30T12:12:17.839Z',
          createdAt: '2024-11-30T12:12:17.742Z',
        },
      ],
      meta: {
        title: 'Digital Horizons: A Glimpse into Tomorrow',
        image: {
          id: 3,
          alt: 'Curving abstract shapes with an orange and blue gradient',
          caption: {
            root: {
              type: 'root',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  type: 'paragraph',
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Photo by ',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                    {
                      type: 'link',
                      fields: {
                        url: 'https://unsplash.com/@kirp',
                        newTab: true,
                        linkType: 'custom',
                      },
                      format: '',
                      indent: 0,
                      version: 2,
                      children: [
                        {
                          mode: 'normal',
                          text: 'Andrew Kliatskyi',
                          type: 'text',
                          style: '',
                          detail: 0,
                          format: 0,
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                    },
                    {
                      mode: 'normal',
                      text: ' on Unsplash.',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                  textFormat: 0,
                },
              ],
              direction: 'ltr',
            },
          },
          updatedAt: '2024-11-30T12:12:09.410Z',
          createdAt: '2024-11-30T12:12:09.410Z',
          url: '/api/media/file/image-post1.webp',
          thumbnailURL: '/api/media/file/image-post1-300x169.webp',
          filename: 'image-post1.webp',
          mimeType: 'image/webp',
          filesize: 15924,
          width: 1920,
          height: 1080,
          focalX: 50,
          focalY: 50,
          sizes: {
            thumbnail: {
              url: '/api/media/file/image-post1-300x169.webp',
              width: 300,
              height: 169,
              mimeType: 'image/webp',
              filesize: 1506,
              filename: 'image-post1-300x169.webp',
            },
            square: {
              url: '/api/media/file/image-post1-500x500.webp',
              width: 500,
              height: 500,
              mimeType: 'image/webp',
              filesize: 3718,
              filename: 'image-post1-500x500.webp',
            },
            small: {
              url: '/api/media/file/image-post1-600x338.webp',
              width: 600,
              height: 338,
              mimeType: 'image/webp',
              filesize: 3506,
              filename: 'image-post1-600x338.webp',
            },
            medium: {
              url: '/api/media/file/image-post1-900x506.webp',
              width: 900,
              height: 506,
              mimeType: 'image/webp',
              filesize: 5718,
              filename: 'image-post1-900x506.webp',
            },
            large: {
              url: '/api/media/file/image-post1-1400x788.webp',
              width: 1400,
              height: 788,
              mimeType: 'image/webp',
              filesize: 9810,
              filename: 'image-post1-1400x788.webp',
            },
            xlarge: {
              url: '/api/media/file/image-post1-1920x1080.webp',
              width: 1920,
              height: 1080,
              mimeType: 'image/webp',
              filesize: 15924,
              filename: 'image-post1-1920x1080.webp',
            },
          },
        },
        description:
          'Dive into the marvels of modern innovation, where the only constant is change. A journey where pixels and data converge to craft the future.',
      },
      publishedAt: '2024-11-30T12:12:18.254Z',
      authors: [
        {
          id: 2,
          name: 'Demo Author',
          workHistory: [],
          certifications: [],
          areasOfExpertise: [],
          profilePicture: null,
          updatedAt: '2024-11-30T12:12:08.651Z',
          createdAt: '2024-11-30T12:12:08.651Z',
          email: 'demo-author@payloadcms.com',
          loginAttempts: 0,
        },
      ],
      populatedAuthors: [{ id: 2, name: 'Demo Author' }],
      slug: 'digital-horizons-a-glimpse-into-tomorrow',
      slugLock: true,
      updatedAt: '2024-11-30T12:12:18.757Z',
      createdAt: '2024-11-30T12:12:18.244Z',
      _status: 'published',
    },
  ],
  hasNextPage: false,
  hasPrevPage: false,
  limit: 10,
  nextPage: null,
  page: 1,
  pagingCounter: 1,
  prevPage: null,
  totalDocs: 3,
  totalPages: 1,
}

const meta: Meta<typeof NewsGrid> = {
  title: 'Website Components/NewsGrid',
  component: NewsGrid,
  tags: ['autodocs'],
  argTypes: {
    // color: {
    //   options: ['primary', 'secondary', 'tertiary', 'quaternary', 'highlight', 'accent', 'muted', 'paper'],
    //   control: { type: 'select' },
    // }
  },
  decorators: [
    (Story: React.FC) => (
      <div className="p-2">
        <Story />
      </div>
    ),
  ],
  parameters: {
    msw: {
      handlers: [
        http.get('/api/posts?page=1', async () => {
          await delay(800)
          return HttpResponse.json(testData)
        }),
      ],
    },
  },
}
export default meta

type Story = StoryObj<typeof NewsGrid>

export const Primary: Story = {
  args: {
    blogs: [
      {
        slug: '/blog/pioneering-progress',
        image: {
          src: '/assets/images/blog/istockphoto1.jpg',
          alt: 'Pioneering Progress, One Algorithm at a Time',
        },
        authors: [ { name: 'admin with a long name'}, { name: 'demo'}],
        categories: ['Technology', 'Other'],
        publishedAt: '2025-01-01T17:19:41.270Z',
        commentCount: '05',
        title: 'Pioneering Progress, One Algorithm at a Time',
        description:
          'Aliquam eros justo, posuere lobortis non, viverra laoreet augue mattis start fermentum ullamcorper viverra laoreet. By Admin. Technology. 28th February 2022. Leave a comment.',
      },
      {
        slug: '/blog/innovative-solutions',
        image: null,
        publishedAt: '2025-01-01T17:19:41.270Z',
        categories: [],
        commentCount: '10',
        title: 'Innovative Solutions for Modern Problems',
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. By John Doe. Innovation. 15th March 2022. Leave a comment.',
      },
      {
        slug: '/blog/future-of-tech',
        image: {
          src: '/assets/images/blog/istockphoto3.jpg',
          alt: 'The Future of Technology',
        },
        authors: [ { name: 'admin'}, { name: 'demo'}],
        publishedAt: '2025-01-01T17:19:41.270Z',
        commentCount: '08',
        title: 'The Future of Technology',
        description:
          'Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. By Jane Doe. Future. 22nd April 2022. Leave a comment.',
      },
    ],
    //   icon: { type: 'thin', name: 'star' },
    //   title : 'Primary Insights',
    //   body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eu ipsum enim.',
    //   color: 'secondary',
  },
}
